site_name: Deployment Pipeline
theme:
  name: material

nav:
  - Home: index.md
  - Functional Documentation:
      - Overview: functional/overview.md
      - Modules: functional/functional-usecases.md
      
  - Use Case Documentation:
      - Business Overview: use-cases/business-overview.md

  - Schema Design: 
      - Tables and ER Diagram: data-modelling/tables-and-er-diagram.md
      - Indexing: data-modelling/indexing.md
  
  - Technical Document:
      - Cloud-Infrastructure: technical-document/architecture.md
      - Data-Flow-Diagram: technical-document/data-flow-diagram.md
      - Authentication-And-Autherization: technical-document/authentication-and-autherization.md
      - Technical Stack: technical-document/technical-stack.md
      - Unit Test Plan: technical-document/test-plan.md
      - CI/CD Pipeline and Deployment Flow: technical-document/ci-cd-pipeline-deployment-flow.md
      - Code Merge Workflow: technical-document/code-merge-workflow.md
      - Security Scanning: technical-document/Security-Scanning.md
plugins:
  - search
  - mermaid2




