site_name: Deployment Pipeline
theme:
  name: material

nav:
  - Home: index.md
  - Functional Documentation:
      - Overview: functional/overview.md
      - Modules: functional/functional-usecases.md
      
  - Use Case Documentation:
      - Business Overview: use-cases/business-overview.md

  - Schema Design: 
      - Tables and ER Diagram: data-modelling/tables-and-er-diagram.md
      - Indexing: data-modelling/indexing.md
plugins:
  - search
  - mermaid2




